server:
    port: 8080
spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/storage-experiments
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master-old.xml
